common: &common
  # setting the course
  hubs:
    -
      num:  1
      diaries:
        -
          title: Saúde e sociedade
          id: 1264
        -
          title: Epidemiologia
          id: 28
    -
      num: 2
      diaries:
        -
          title: Gestão e Avaliação na Atenção Básica
          id: 28
        -
          title: Planejamento na Atenção Básica
          id: 28
        -
          title: Processo de Trabalho na Atenção Básica
          id: 28
    -
      num: 3
      diaries:
        -
          title: Atenção Integral na Saúde da Criança/ Apoio Matricial
          id: 28
        -
          title: Atenção Integral na Saúde da Mulher/Clínica Ampliada
          id: 28
        -
          title: Atenção Integral na Saúde do Adulto/Projeto Terapêutico Singular
          id: 28
        -
          title: Atenção Integral Saúde do Idoso/Projeto de Saúde no Território
          id: 28

development:
  <<: *common
  server: http://localhost/moodle/webservice/rest/server.php
  token: a50253670439cc22ab223d1af67e305b

  consumer_key: consumer_key
  consumer_secret: consumer_secret

test:
  <<: *common
  server: http://localhost/moodle/webservice/rest/server.php
  token: a50253670439cc22ab223d1af67e305b

  consumer_key: consumer_key
  consumer_secret: consumer_secret

production:
  <<: *common
#  server:
#  token:

#  consumer_key:
#  consumer_secret:
